version: "3.8"

services:
  dashboard:
    image: gontcharovd/ccp-dashboard:latest
    ports:
      - "3838:3838"
    network_mode: host
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
    container_name: dashboard_container
  pipeline:
    image: gontcharovd/ccp-pipeline:custom_airflow
    ports:
      - "8080:8080"
      - "5432:5432"
    network_mode: host
    environment:
      - AIRFLOW_CONN_COGNITE=${AIRFLOW_CONN_COGNITE}
      - COGNITE_API_KEY=${COGNITE_API_KEY}
      - COGNITE_CLIENT_NAME=${COGNITE_CLIENT_NAME}
      - COGNITE_PROJECT=${COGNITE_PROJECT}
    volumes:
      - /var/log/supervisor-ccp-pipeline:/var/log/supervisor
    container_name: pipeline_container
